
#####################################################################
# Is git LFS required to run this repository?
#
# This normally remain "Yes", as this prevents inadvertently
# committing large data files
#####################################################################
git_lfs_required: Yes

#####################################################################
# Other required software
#####################################################################
gslab_make_required: Yes

software_required:
  r: Yes
  stata: Yes
  lyx: Yes
  matlab: No
  latex: No

#####################################################################
# Maximum allowed file sizes
#####################################################################
max_file_sizes:
  file_MB_limit_lfs: 100         # Soft limit on file size (w/ LFS)
  total_MB_limit_lfs: 500        # Soft limit on total size (w/ LFS)  
  file_MB_limit: 0.5             # Soft limit on file size (w/o LFS)
  total_MB_limit: 100            # Soft limit on total size (w/o LFS)

#####################################################################
# default within-repo paths
#####################################################################
make_paths:
  root_relative:
    lib: lib
    config: config.yaml
    config_user: config_user.yaml
  absolute:
    input_dir: input
    external_dir: external
    output_dir: output
    output_local_dir: output_local
    makelog: log/make.log
    output_statslog: log/output_stats.log
    source_maplog: log/source_map.log
    source_statslog: log/source_stats.log
  